name: weight_scale_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # flutter_blue_plus: 
  permission_handler: 
  shared_preferences: 
  image_picker: 
  get: 
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/