// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF0JbaR9ABlMPJcfvnqrFEWaINXVkh3F8',
    appId: '1:60489026538:web:58e9afa4973b1662c80093',
    messagingSenderId: '60489026538',
    projectId: 'weight-scale-371f5',
    authDomain: 'weight-scale-371f5.firebaseapp.com',
    databaseURL: 'https://weight-scale-371f5-default-rtdb.firebaseio.com',
    storageBucket: 'weight-scale-371f5.firebasestorage.app',
    measurementId: 'G-49E16CGKX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA81xqxPPDZrDbSVGcBOK4q9nsb9n_F90c',
    appId: '1:60489026538:android:74e61c58009552dec80093',
    messagingSenderId: '60489026538',
    projectId: 'weight-scale-371f5',
    databaseURL: 'https://weight-scale-371f5-default-rtdb.firebaseio.com',
    storageBucket: 'weight-scale-371f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK-Zus-9ocvRFMBi3zJhqGgxflYm66WJ4',
    appId: '1:60489026538:ios:5a0fe3faccf78e92c80093',
    messagingSenderId: '60489026538',
    projectId: 'weight-scale-371f5',
    databaseURL: 'https://weight-scale-371f5-default-rtdb.firebaseio.com',
    storageBucket: 'weight-scale-371f5.firebasestorage.app',
    iosBundleId: 'com.example.weightScaleV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK-Zus-9ocvRFMBi3zJhqGgxflYm66WJ4',
    appId: '1:60489026538:ios:5a0fe3faccf78e92c80093',
    messagingSenderId: '60489026538',
    projectId: 'weight-scale-371f5',
    databaseURL: 'https://weight-scale-371f5-default-rtdb.firebaseio.com',
    storageBucket: 'weight-scale-371f5.firebasestorage.app',
    iosBundleId: 'com.example.weightScaleV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF0JbaR9ABlMPJcfvnqrFEWaINXVkh3F8',
    appId: '1:60489026538:web:32388b59bf0239c5c80093',
    messagingSenderId: '60489026538',
    projectId: 'weight-scale-371f5',
    authDomain: 'weight-scale-371f5.firebaseapp.com',
    databaseURL: 'https://weight-scale-371f5-default-rtdb.firebaseio.com',
    storageBucket: 'weight-scale-371f5.firebasestorage.app',
    measurementId: 'G-XZKCY8HQP8',
  );
}
